[package]
name = "ntk-export"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
ntk-core = { path = "../ntk-core" }
anyhow.workspace = true
clap.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
